# Generated by Django 3.2.9 on 2021-11-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('fam', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=200)),
                ('ish_joy', models.CharField(max_length=200)),
                ('telefon_raqam', models.IntegerField()),
                ('maxsulot_nomi', models.CharField(max_length=800)),
                ('soni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Happy_clents1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=40)),
                ('rasmi', models.ImageField(upload_to='media/')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Happy_clents2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=40)),
                ('rasmi', models.ImageField(upload_to='media/')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Happy_clents3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=40)),
                ('rasmi', models.ImageField(upload_to='media/')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Onemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.EmailField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
                ('old_prise', models.IntegerField()),
                ('new_prise', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('chegirma', models.CharField(max_length=4, null=True)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('rangi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploying.rang')),
                ('turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploying.tur')),
            ],
        ),
        migrations.CreateModel(
            name='Chegirmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
                ('narxi', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('rangi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploying.rang')),
                ('turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploying.tur')),
            ],
        ),
    ]
