# Generated by Django 3.2.5 on 2021-11-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploying', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploying.rang')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploying.tur')),
            ],
        ),
    ]
